figure;
x = 0:0.2:2*pi; 
subplot(2, 1, 1); 
y_sin = sin(x); 
hold on;
plot(x, y_sin, 'b', 'LineWidth', 2);
y_cos = cos(x); 
plot(x, y_cos, 'r+--', 'LineWidth', 2); 
title('Sine and Cosine Wave'); 
ylabel('Value'); 
legend('sin(x)', 'cos(x)');
grid on;
hold off;
