figure;
radius = 1;
pointCount = 50;
t = linspace(0, 2*pi, pointCount);
s = linspace(0, 2*pi, pointCount);
[T, S] = meshgrid(t, s);
X = radius * cos(T) .* cos(S);
Y = radius * cos(T) .* sin(S);
Z = radius * sin(T);
surf(X, Y, Z, 'FaceColor', 'b', 'EdgeColor', 'none');
shading interp;
hold on;
mesh(X, Y, Z, 'EdgeColor', 'k', 'FaceColor', 'none');
title('3D Plot of a Sphere');
xlabel('X-axis');
ylabel('Y-axis');
zlabel('Z-axis');
axis equal;
grid on;
colorbar;
view(30, 30);
hold off;